### PR TITLE
closed the output stream so that the file handle gets let go sooner

### PR DESCRIPTION
**Pull request by Lucas-S**
I noticed that in our production environment that sometimes this would go through its 20 retries and bomb out really quickly. If I closed the output stream at the end, it got much happier!

### CODE REVIEW

**Comment by xivSolutions** [comment]
Cool thanks!

Did you say "production environment?" 

If so, are there any API/structural changes you would make? How is it working, and how are you using it (to the degree you can share)?

**Comment by Lucas-S** [comment]
it works well (almost) in the environment we have it in. The largest
problems we have with it is that we get 'file locked' errors from time to
time.
I have been thinking about putting a lock around the write to 'slow down'
the writes and single thread it to also help keeping the file from locking.

we will see how this change goes.

**Comment by xivSolutions** [comment]
I assume the file locking issues are related to concurrent access? That was the primary challenge with the file/JSON store (and what finally drove Rob to try on some database back-ends as well). 

I've been debating between trying to solve the concurrency problem, or pushing the notion that when concurrency issues arise, it's time to move to SQLite or PG.

**Comment by Lucas-S** [comment]
Yeah, I was almost to that point. The json packets just make it so easy to
debug (client side)


-------------
Sent on the go ( from the phone )
Sorry for being so short & for any bad typos or spelling

On 27 Feb 2015, at 10:33 pm, John Atten <notifications@github.com> wrote:

I assume the file locking issues are related to concurrent access? That was
the primary challenge with the file/JSON store (and what finally drove Rob
to try on some database back-ends as well).

I've been debating between trying to solve the concurrency problem, or
pushing the notion that when concurrency issues arise, it's time to move to
SQLite or PG.

—
Reply to this email directly or view it on GitHub
<https://github.com/xivSolutions/biggy/pull/26#issuecomment-76381499>.

**Comment by xivSolutions** [comment]
Keep us posted. I haven't done much here in a bit, but I am actively looking for feedback as to which direction to take this. Actual use is the very best indicator...

**Pull request merged**
